pub const STATE_FILE: &str = "state.json";
pub const STATE_SCHEMA_VERSION: u32 = 2;
pub const DEFAULT_CLOUD_URL: &str = match option_env!("COOP_CLOUD_URL") {
    Some(value) => value,
    None => "https://api.co-op.software",
};
pub const DEFAULT_OLLAMA_URL: &str = "http://localhost:11434";
pub const REQUEST_TIMEOUT_SECS: u64 = 30;
pub const MIN_RUN_TOKENS: u32 = 256;
pub const MAX_RUN_TOKENS: u32 = 64000;
pub const MAX_MODEL_NAME_LENGTH: usize = 128;
pub const MAX_OBJECTIVE_LENGTH: usize = 8000;
pub const MAX_DOCUMENT_LENGTH: usize = 250_000;
pub const RAG_VECTOR_DIMENSIONS: usize = 128;
pub const MAX_CHAT_HISTORY_MESSAGES: usize = 40;
pub const MAX_STORED_WORKFLOW_RUNS: usize = 100;
pub const MAX_CHAT_SESSIONS: usize = 200;
pub const MAX_DOCUMENTS: usize = 500;
pub const MAX_RESEARCH_RUNS: usize = 250;
pub const MAX_LEADS: usize = 10_000;
pub const MAX_CAMPAIGNS: usize = 500;
pub const MAX_CAMPAIGN_EMAILS: usize = 25_000;
pub const MAX_CAMPAIGN_SEND_BATCH: usize = 100;
pub const MAX_GENERATED_EMAILS_PER_CAMPAIGN: usize = 500;
pub const MAX_EMAIL_BODY_LENGTH: usize = 20_000;
pub const MAX_EMAIL_SUBJECT_LENGTH: usize = 180;
pub const MAX_ALERTS: usize = 250;
pub const MAX_PITCH_DECKS: usize = 250;
pub const MAX_CAP_TABLES: usize = 250;
pub const MAX_BOOKMARKS: usize = 1_000;
pub const MAX_INTEGRATIONS: usize = 250;
pub const APP_VERSION_FALLBACK: &str = "1.0.0";
