import type { DesktopState, StartupProfile } from './types';

const emptyWorkspace: StartupProfile = {
  founderName: '',
  founderRole: 'founder',
  companyName: '',
  tagline: '',
  website: '',
  description: '',
  stage: 'idea',
  industry: '',
  sector: 'other',
  location: '',
  country: '',
  city: '',
  operatingRegions: '',
  teamSize: '',
  cofounderCount: null,
  targetCustomers: '',
  problem: '',
  solution: '',
  businessModel: '',
  revenueModel: 'not_yet',
  isRevenue: 'pre_revenue',
  monthlyRevenue: null,
  fundingStage: 'bootstrapped',
  totalRaised: null,
  traction: '',
  competitiveAdvantage: '',
  goals: '',
  foundedYear: null,
  launchDate: '',
  updatedAt: new Date(0).toISOString(),
  onboardingCompletedAt: null,
};

export const previewState: DesktopState = {
  installId: 'web-preview',
  activation: null,
  isUsable: false,
  workflowRuns: [],
  workspace: emptyWorkspace,
  chatSessions: [],
  documents: [],
  researchRuns: [],
  leads: [],
  campaigns: [],
  campaignEmails: [],
  investors: [],
  alerts: [],
  pitchDecks: [],
  capTables: [],
  bookmarks: [],
  integrations: [],
  modelSettings: {
    provider: 'ollama',
    ollamaBaseUrl: 'http://localhost:11434',
    ollamaModel: 'llama3.1',
    openaiBaseUrl: 'https://api.openai.com/v1',
    openaiModel: 'gpt-4.1-mini',
    openaiApiKeySaved: false,
    councilMode: 'review_only',
    maxRunTokens: 12000,
    researchProvider: 'llm',
    firecrawlBaseUrl: 'https://api.firecrawl.dev',
    firecrawlApiKeySaved: false,
    emailProvider: 'none',
    emailApiKeySaved: false,
    emailFrom: '',
    emailFromName: '',
  },
};
