import type { DesktopState, StartupProfile } from './types';

const now = '2026-06-12T00:00:00.000Z';

const previewWorkspace: StartupProfile = {
  founderName: 'Maya Rao',
  founderRole: 'Founder',
  companyName: 'Sample Company',
  tagline: 'Customer operations for service businesses',
  website: 'https://example.com',
  description:
    'A sample business uses Co-Op to organize customer follow-ups, quotes, and recurring work.',
  stage: 'launched',
  industry: 'Business software',
  sector: 'saas',
  location: 'Bengaluru, India',
  country: 'India',
  city: 'Bengaluru',
  operatingRegions: 'India, US',
  teamSize: '6-20',
  cofounderCount: 1,
  targetCustomers: 'Owner-led service businesses with repeat customers and manual follow-up work.',
  problem: 'Customer follow-ups, quote tracking, and weekly operating reviews are spread across tools.',
  solution: 'A private workspace that turns company context into plans, research, and customer actions.',
  businessModel: 'b2b',
  revenueModel: 'subscription',
  isRevenue: 'revenue',
  monthlyRevenue: 18000,
  fundingStage: 'bootstrapped',
  totalRaised: 0,
  traction: '42 active customers, 11 percent month-over-month growth, strong referral pipeline.',
  competitiveAdvantage: 'Local-first workflows, practical business memory, and simple owner controls.',
  goals: 'Improve onboarding, increase qualified pipeline, and prepare for a seed conversation.',
  foundedYear: 2025,
  launchDate: '2026-01-15',
  updatedAt: now,
  onboardingCompletedAt: now,
};

export const previewState: DesktopState = {
  installId: 'web-preview',
  activation: {
    customerEmail: 'owner@example.com',
    plan: 'team',
    status: 'active',
    expiresAt: null,
    features: ['local_workspace', 'private_provider', 'business_tools'],
    offlineGraceEndsAt: '2026-07-12T00:00:00.000Z',
    lastHeartbeatAt: now,
    cloudBaseUrl: 'https://api.co-op.software',
  },
  isUsable: true,
  workflowRuns: [
    {
      id: 'run-preview-1',
      workflowType: 'operations',
      objective: 'Create a 30-day customer pipeline plan',
      provider: 'openai_compatible',
      status: 'completed',
      steps: ['Loaded company context', 'Reviewed saved files', 'Drafted plan', 'Checked risks'],
      trace: [
        {
          id: 'trace-preview-1',
          stage: 'Context',
          label: 'Loaded company profile',
          status: 'done',
          detail: 'Company profile and current goals were included.',
          createdAt: now,
        },
        {
          id: 'trace-preview-2',
          stage: 'Work',
          label: 'Prepared operating plan',
          status: 'done',
          detail: 'Pipeline, onboarding, and review cadence were converted into next steps.',
          createdAt: now,
        },
      ],
      riskLevel: 'normal',
      approvalRequired: false,
      output:
        'Focus the next 30 days on three moves: tighten onboarding, run a weekly pipeline review, and follow up with the 18 highest-fit prospects already identified.',
      error: null,
      createdAt: now,
      completedAt: now,
    },
  ],
  workspace: previewWorkspace,
  chatSessions: [
    {
      id: 'chat-preview-1',
      title: 'Weekly operating plan',
      agentType: 'operations',
      messages: [
        {
          id: 'message-preview-1',
          role: 'user',
          content: 'What should we focus on this week?',
          agentType: null,
          createdAt: now,
        },
        {
          id: 'message-preview-2',
          role: 'assistant',
          content:
            'Prioritize onboarding fixes, pipeline follow-ups, and one pricing review. I used your company profile and saved files.',
          agentType: 'operations',
          createdAt: now,
        },
      ],
      a2aEnabled: true,
      ragEnabled: true,
      researchEnabled: true,
      councilMode: 'review_only',
      createdAt: now,
      updatedAt: now,
    },
  ],
  documents: [
    {
      id: 'doc-preview-1',
      title: 'Customer onboarding notes',
      source: 'local file',
      content: '',
      chunkCount: 8,
      chunks: [],
      createdAt: now,
    },
    {
      id: 'doc-preview-2',
      title: 'Pipeline review memo',
      source: 'local file',
      content: '',
      chunkCount: 6,
      chunks: [],
      createdAt: now,
    },
  ],
  researchRuns: [
    {
      id: 'research-preview-1',
      query: 'Pricing signals for service-business operations software',
      provider: 'firecrawl',
      summary:
        'Comparable products package simple team plans around customer follow-up, reporting, and owner visibility. Usage limits are clearer when tied to seats, contacts, or workspaces.',
      sources: [
        {
          title: 'Market scan',
          url: 'https://example.com/research',
          description: 'Sample research source',
          content: 'Pricing and packaging notes for preview state.',
        },
      ],
      createdAt: now,
    },
  ],
  leads: [
    {
      id: 'lead-preview-1',
      leadType: 'customer',
      name: 'Jordan Lee',
      companyName: 'Brightline Services',
    email: 'customer.one@example.com',
      website: 'https://brightline.example',
      profileUrl: '',
      platform: 'web',
      niche: 'field services',
      location: 'Austin, TX',
      description: 'Owner-led service business with repeat-customer follow-up needs.',
      leadScore: 82,
      status: 'qualified',
      source: 'research',
      createdAt: now,
    },
    {
      id: 'lead-preview-2',
      leadType: 'customer',
      name: 'Priya Menon',
      companyName: 'CareFlow Clinics',
    email: 'customer.two@example.com',
      website: 'https://careflow.example',
      profileUrl: '',
      platform: 'web',
      niche: 'clinics',
      location: 'Mumbai, India',
      description: 'Clinic operator with manual reminders and weekly reporting gaps.',
      leadScore: 76,
      status: 'qualified',
      source: 'research',
      createdAt: now,
    },
  ],
  campaigns: [
    {
      id: 'campaign-preview-1',
      name: 'Owner follow-up sequence',
      mode: 'draft',
      targetLeadType: 'customer',
      subjectTemplate: 'A simpler way to review weekly follow-ups',
      bodyTemplate: 'Personalized draft prepared locally.',
      campaignGoal: 'Book discovery calls',
      tone: 'clear',
      callToAction: 'Ask for a short call',
      status: 'draft',
      createdAt: now,
    },
  ],
  campaignEmails: [],
  investors: [],
  alerts: [
    {
      id: 'alert-preview-1',
      name: 'Competitor pricing watch',
      query: 'pricing changes in service operations software',
      cadence: 'weekly',
      enabled: true,
      lastResult: 'No major packaging changes found this week.',
      createdAt: now,
    },
  ],
  pitchDecks: [
    {
      id: 'pitch-preview-1',
      title: 'Seed narrative review',
      deckNotes: 'Uploaded pitch deck notes',
      sourceFileName: 'sample-seed-deck.pdf',
      slideCount: 12,
      score: 81,
      analysis: 'Strong customer pain and early traction. Clarify pricing and sales motion before investor meetings.',
      createdAt: now,
    },
  ],
  capTables: [],
  bookmarks: [],
  integrations: [],
  modelSettings: {
    provider: 'openai_compatible',
    ollamaBaseUrl: 'http://localhost:11434',
    ollamaModel: 'llama3.1',
    openaiBaseUrl: 'https://api.openai.com/v1',
    openaiModel: 'gpt-4.1-mini',
    openaiApiKeySaved: true,
    councilMode: 'review_only',
    maxRunTokens: 12000,
    researchProvider: 'firecrawl',
    firecrawlBaseUrl: 'https://api.firecrawl.dev',
    firecrawlApiKeySaved: true,
    emailProvider: 'resend',
    emailApiKeySaved: true,
    emailFrom: 'hello@example.com',
    emailFromName: 'Sample Company',
  },
};
